version: "3.8"

services:

  alert-svc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alert-svc
    environment:
      - NODE_ENV=${NODE_ENV}
      - KAFKA_HOST=${KAFKA_HOST}
      - API_PREFIX=${API_PREFIX}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - PORT=3004
    networks:
      - backend
    ports:
      - "3004:3004"

networks:
  backend:
    driver: bridge
