apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: alert-svc
  name: alert-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alert-svc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: alert-svc
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: NODE_ENV
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: KAFKA_HOST
            - name: API_PREFIX
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: API_PREFIX
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: SENDGRID_API_KEY
            - name: FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: FROM_EMAIL
            - name: PORT
              value: "3004"
          image: ghcr.io/fis2425/alert:latest
          name: alert-svc
          ports:
            - containerPort: 3004
              protocol: TCP
      restartPolicy: Always
